//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblLanguage
    {
        
        //[Required(ErrorMessage = "Language is required")]

        public int colLanguageId { get; set; }
      //  [Required(ErrorMessage = "Language is required")]

        public string colLanguageName { get; set; }
        public string colLanguageShortName { get; set; }
    }
}
