//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblLevel
    {

     //   [Required(ErrorMessage = "Level is required")]

        public int colLevelId { get; set; }
        public string colLevelName { get; set; }
        public string colLevelDescription { get; set; }
    }
}
