//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSyllabu
    {
        public int colSyllabusId { get; set; }
        public string colSyllabusName { get; set; }
        public int colTradeId { get; set; }
        public int colLevelId { get; set; }
        public string colSyllabusDocUrl { get; set; }
        public string colTestPlanUrl { get; set; }
        public string colDevelopmentOfficer { get; set; }
        public string colManager { get; set; }
        public System.DateTime colActiveDt { get; set; }
        public bool colSt { get; set; }
    }
}
