//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTrade
    {

     //   [Required(ErrorMessage = "Trade is required")]

        public int colTradeId { get; set; }
        public string colTradeName { get; set; }
        public string colAbbreviation { get; set; }
    }
}
